ALTER TABLE profiles ADD COLUMN IF NOT EXISTS nationality text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS citizenship_status text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS work_permit_required boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS work_permit_expiry_date text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS mailing_address text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS alternate_phone text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS employment_length text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS employer_address text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS monthly_gross_income numeric DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS monthly_net_income numeric DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS other_income_amount numeric DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS other_income_description text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS loan_purpose text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS requested_loan_amount numeric DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS desired_loan_term_years integer;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS property_type text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS property_location text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS property_identified boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS purchase_agreement_available boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS primary_bank_name text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS existing_bank_relationship boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bank_statements_available boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS missed_payments_history boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bankruptcy_history boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_id boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_proof_of_address boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_payslips boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_employment_letter boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_bank_statements boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_debt_statements boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_credit_report boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_purchase_agreement boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_valuation boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_down_payment_proof boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_business_financials boolean DEFAULT false;
